name: kylecyree.com
favicon: null
layout_spectrum: 0.9118640765082091
typography_spectrum: 0.46440386259928346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2581963795237243
  lightness: 0.10790335480123758
  saturation: 0.6354604554362595
  rhythmicContrast: 0.6494256658479571
purpose: []
